### PR TITLE
WIP: Added the docker namespacing functionality.

### PR DESCRIPTION
**Pull request by frob**
This feature branch adds the ability to add custom namespacing to the docker images that are built with this project. 

## API changes

This removes the existing variable `OPENEDX_DOCKER_IMAGE` and replaces it with individual pieces that allow for finer control. The new variables are also set to work with the makefile so `make build` (and other docker image commands) will continue to work.

The new variables are:

```
OPENEDX_DOCKER_NAMESPACE
OPENEDX_DOCKER_IMAGE_PREFIX
OPENEDX_DOCKER_TAG
```

These have defaults values that are backward compatible with the current default docker image.

### CODE REVIEW

**Comment by frob** [comment]
Agh, my computer died as I was finishing this PR. Back to it now.

**Comment by frob** [comment]
Okay, tech issues aside I force pushed the branch and it should be ready for PR.

**Comment by regisb** [comment]
Hi @frob! Thanks for creating this PR! The changes you propose are rather substantial and make the docker-compose* files much harder to read. I see the point of using a different openedx image, but do you think it's a useful feature to run different images for notes/xqueue? I must admit I'm not a big fan of the change, but maybe I fail to see your use case here. Maybe you can tell me more about the problem you are trying to solve?

**Comment by frob** [comment]
@regisb sorry, I took Christmas off completely --so now I am getting back to this. 

It looks like notes and xqueue are their own codebases and thus the possibility could exist that they need their own containers. At the very least I feel a custom namespace is required as forcing anyone using this repo as their base will mean forcing them to use your regis namespaced images as their base and for some clients that simply isn't going to work. 

I defininatly see the issue with the names being unreadable in the compose files. Maybe the assebly of the namespaces could be done in the Makefile instead and that would leave a single env variable used for the image:

```
  image: $(XQUEUEDOCKERIMAGE)
```

or, to make the default self documented:

```
  image: $(XQUEUEDOCKERIMAGE:-regis/openedx-xqueue:hawthorn)
```

From the looks of it, much work has been done so I will have to refactor whatever I do anyway.

**Comment by regisb** [comment]
> forcing anyone using this repo as their base will mean forcing them to use your regis namespaced images as their base and for some clients that simply isn't going to work.

Why is that? I was considering of renaming the docker image to a more "professional-sounding" repo that would correspond to my company. Would that work?

**Comment by frob** [comment]
Some projects/clients require more control over the stack. Also, imagine needing another patch or customization for a one off. Or not a requirement to not mix images. For 85% of use-cases, yes, an official sounding namespace would be enough, but for the more difficult 15%, which I could see myself having as clients, this would be a nice addition.

Let see if I can make this less of an encumbrance by moving the assembly of the image names into the Makefile.

**Comment by frob** [comment]
Wow, so much has changed I think we need some discussion before this moves forward again.

Closing for now as this branch is now woefully out of date. Discussion can continue in #122

**Pull request closed without merging**
